### PR TITLE
feat: add eight new actions

### PR DESCRIPTION
**Pull request by axolotlmaid**
Please let me know if there is any problems.

## Changes / additions
- Add replay buffer (saving and toggling)
- Switch scene collections
- Toggle mute on inputs
- Toggle scene items
- Toggle virtual camera
- Trigger transition
- Toggle studio mode
- Bumped version up to 1.0.1

### CODE REVIEW

**Comment by Core447** [comment]
Nice work! However, I still experience some issues with the error handling, I'm getting the following:

File "StreamController/data/plugins/com_core447_OBSPlugin/backend/backend.py", line 82, in get_replay_buffer_status
    "active": status.datain["outputActive"]
              ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'outputActive'

And it would be nice to have default icons for all actions, even when obs is not connected.

**Comment by axolotlmaid** [comment]
Alright, I will look into adding your suggestions. Also that error appears when you don't have replay buffer enabled.

**Comment by axolotlmaid** [comment]
Hello, I have added your suggestions. It now warns the user in the logs if an expected error happens. I also made it so that icons are never empty and show the error icon instead. Let me know if you want more changes.

**Comment by Core447** [comment]
Perfect, great work, thank you!

**Pull request merged**
