### PR TITLE
fix: proper error handling

### PR DESCRIPTION
**Pull request by Sorunome**
Together with https://github.com/StreamController/StreamController/pull/122 this will remove the message spam and properly update the icon label to be an error label

### CODE REVIEW

**Comment by Core447** [comment]
Thank you very much! However, I don't see how this affects the command line output, or what spamming do you mean?

**Comment by Sorunome** [comment]
Together without https://github.com/StreamController/StreamController/pull/122 it was spamming the log greatly. Additionally, the error icon wasn't handled properly and the backend object was created too early

30. 5. 2024 21:00:53 Core447 ***@***.***>:

**Comment by Sorunome** [comment]
yup, sounds good. not sure if that will work with the current stable release, though

2. 6. 2024 13:28:50 Core447 ***@***.***>:

**Comment by Core447** [comment]
> yup, sounds good. not sure if that will work with the current stable release, though

It should work, because the error was added after the release

**Comment by Core447** [comment]
Added the `self.hide_error()` line in 24ed6eda83d3397fd7551179dd8c48e27decae0a

**Pull request closed without merging**
